<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-DI9KG3PP" failures="1" tests="3" name="CRUDTest Exception" time="0.058" errors="0" timestamp="2023-03-06T22:52:41 ICT">
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues1" time="0.001"/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues2" time="0.001"/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues3" time="0.056">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest.testCreateCharacterWithValues3(CharacterCRUDNGTest.java:55)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testCreateCharacterWithValues3 -->
</testsuite> <!-- CRUDTest Exception -->
