<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DI9KG3PP" failures="1" tests="5" name="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" time="53.070" errors="0" timestamp="2023-03-06T23:03:14 ICT" skipped="0">
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues3" time="0.410"/>
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues2" time="0.000"/>
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testDeleteCharacterWithGivenRightArgumentReturnWell" time="43.207">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1066)
at org.testng.Assert.assertEquals(Assert.java:1030)
at org.testng.Assert.assertEquals(Assert.java:1076)
at org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest.testDeleteCharacterWithGivenRightArgumentReturnWell(CharacterCRUDNGTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.afterRun(TestRunner.java:914)
at org.testng.TestRunner.run(TestRunner.java:605)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- testDeleteCharacterWithGivenRightArgumentReturnWell -->
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testDeleteCharacterWithGivenRightArgumentReturnWell" time="9.437"/>
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest" name="testCreateCharacterWithValues1" time="0.016"/>
  <system-out/>
</testsuite> <!-- org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest -->
